filenameR = 'running1 .xls';
filenameW = 'walking1.xls';
filenameD1 = 'downstairs 1.csv';
filenameD2 = 'downstairs 2.csv';
filenameD3 = 'downstairs 3.csv';
filenameD4 = 'downstairs 4.csv';
filenameD5 = 'downstairs 5.csv';
filenameD6 = 'downstairs 6.csv';
filenameD7 = 'downstairs 11.csv';
filenameD8 = 'downstairs 12.csv';
filenameD9 = 'downstairs 13.csv';
filenameD10 = 'downstairs 18.csv';
filenameD11 = 'downstairs 21.csv';
filenameD12 = 'downstairs 22.csv';
filenameD13 = 'downstairs 23.csv';
filenameD14 = 'downstairs 24.csv';
filenameD15 = 'downstairs 31.csv';
filenameD16 = 'downstairs 33.csv';
filenameD17 = 'downstairs 36.csv';
filenameD18 = 'downstairs 37.csv';
filenameD19 = 'downstairs 38.csv';
filenameU1 = 'upstairs 1.csv';
filenameU2 = 'upstairs 2.csv';
filenameU3 = 'upstairs 3.csv';
filenameU4 = 'upstairs 4.csv';
filenameU5 = 'upstairs 11.csv';
filenameU6 = 'upstairs 12.csv';
filenameU7 = 'upstairs 13.csv';
filenameU8 = 'upstairs 14.csv';
filenameU9 = 'upstairs 15.csv';
filenameU10 = 'upstairs 16.csv';
filenameU11 = 'upstairs 17.csv';
filenameU12 = 'upstairs 21.csv';
filenameU13 = 'upstairs 22.csv';
filenameU14 = 'upstairs 23.csv';
filenameU15 = 'upstairs 24.csv';
filenameU16 = 'upstairs 31.csv';
filenameU17 = 'upstairs 32.csv';
filenameU18 = 'upstairs 33.csv';
filenameU19 = 'upstairs 34.csv';
filenameU20 = 'upstairs 36.csv';

%training
m = xlsread(filenameR,'A2:C21');
trainData3 = reshape(m,1,[]);
m = xlsread(filenameR,'A12:C31');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameR,'A22:C41');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameR,'A32:C51');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameR,'A42:C61');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameR,'A52:C71');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameR,'A62:C81');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameR,'A72:C91');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameR,'A82:C101');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameR,'A92:C111');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);

m = xlsread(filenameW,'A2:C21');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameW,'A12:C31');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameW,'A22:C41');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameW,'A32:C51');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameW,'A42:C61');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameW,'A52:C71');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameW,'A62:C81');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameW,'A72:C91');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameW,'A82:C101');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameW,'A92:C111');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);

m = xlsread(filenameD1,'A2:C21');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameD2,'A2:C21');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameD3,'A2:C21');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameD4,'A2:C21');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameD5,'A2:C21');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameD6,'A2:C21');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameD7,'A2:C21');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameD8,'A2:C21');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameD9,'A2:C21');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameD10,'A2:C21');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);

m = xlsread(filenameU1,'A2:C21');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameU2,'A2:C21');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameU3,'A2:C21');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameU4,'A2:C21');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameU5,'A2:C21');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameU6,'A2:C21');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameU7,'A2:C21');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameU8,'A2:C21');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameU9,'A2:C21');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);
m = xlsread(filenameU10,'A2:C21');
k = reshape(m,1,[]);
trainData3 = cat(1,trainData3,k);

for i=1:10
    trainClass3(i) = 1; %running
end
for i=11:20
    trainClass3(i) = 2; %walking
end
for i=21:30
    trainClass3(i) = 3; %downstairs
end
for i=31:40
    trainClass3(i) = 4; %upstairs
end


 %test
 m = xlsread(filenameR,'A112:C131');
testData3 = reshape(m,1,[]);
m = xlsread(filenameR,'A122:C141');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameR,'A132:C151');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameR,'A142:C161');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameR,'A152:C171');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameR,'A162:C181');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameR,'A172:C191');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameR,'A182:C201');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameR,'A192:C211');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameR,'A202:C221');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
 
m = xlsread(filenameW,'A112:C131');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameW,'A122:C141');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameW,'A132:C151');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameW,'A142:C161');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameW,'A152:C171');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameW,'A162:C181');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameW,'A172:C191');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameW,'A182:C201');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameW,'A192:C211');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameW,'A202:C221');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);

m = xlsread(filenameD11,'A2:C21');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameD12,'A2:C21');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameD13,'A2:C21');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameD14,'A2:C21');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameD15,'A2:C21');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameD16,'A2:C21');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameD17,'A2:C21');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameD18,'A2:C21');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameD19,'A2:C21');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameD10,'A2:C21');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);

m = xlsread(filenameU11,'A2:C21');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameU12,'A2:C21');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameU13,'A2:C21');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameU14,'A2:C21');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameU15,'A2:C21');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameU16,'A2:C21');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameU17,'A2:C21');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameU18,'A2:C21');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameU19,'A2:C21');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);
m = xlsread(filenameU20,'A2:C21');
k = reshape(m,1,[]);
testData3 = cat(1,testData3,k);

%model KNN
ml = ClassificationKNN.fit(trainData3,trainClass3,'NSMethod','exhaustive','Distance','cosine');
m1.NumNeighbors = 2; % k value
rloss = resubLoss(ml)
 cvmd2 = crossval(ml);
 kloss = kfoldLoss(cvmd2)
 
 %model Naive Bayes
 ml1 = NaiveBayes.fit(trainData3,trainClass3);
 
 %prediction
testClassKNN = predict(ml,testData3);
testClassBayes = predict(ml1,testData3);

%confusion matrix
[KNNC1 orderKNN1]= confusionmat(trainClass3,testClassKNN)
[BayesC1 orderBayes1] = confusionmat(trainClass3,testClassBayes)


 



